name: PetNote

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        env_file: .env
        environment:
            DB_HOST: petnote-db
        command: ["/usr/bin/supervisord"]
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network

    db:
        image: mysql:latest
        hostname: petnote-db
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - ./Lucifer.sql:/home/Lucifer.sql
            - ./db.sh:/docker-entrypoint-initdb.d/db.sh
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 2s
            timeout: 3s
            retries: 40
        networks:
            - app-network

networks:
    app-network:
        driver: bridge